// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userID"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
